name: Appsec il
on: push

jobs:
  appsearch:
    runs-on: ubuntu-latest
    name: Hellow word
    steps:
      - run: echo "Hellow Appsec 2023"
      - run: id
      - run: umane -a
      - run: env
      - run: ps
      
